services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: senkou-catalyst-app-dev
    restart: unless-stopped
    environment:
      - APP_PORT=5556
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-senkou_catalyst_dev}
      - JWT_SECRET=${JWT_SECRET:-}
    depends_on:
      - postgres
    networks:
      - catalyst-dev-network

  postgres:
    image: postgres:17-alpine
    container_name: senkou-catalyst-postgres-dev
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-}
      - POSTGRES_DB=${DB_NAME:-senkou_catalyst}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - catalyst-dev-network

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: senkou-catalyst-cloudflare-dev
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol http2 run --token ${TUNNEL_TOKEN:-}
    networks:
      - catalyst-dev-network

networks:
  catalyst-dev-network:
    name: catalyst-dev-network
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
