services:
  postgres:
    image: postgres:17-alpine
    container_name: senkou-catalyst-postgres-dev
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-}
      - POSTGRES_DB=${DB_NAME:-senkou_catalyst}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - catalyst-dev-network

  redis:
    image: redis:7-alpine
    container_name: senkou-catalyst-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data_dev:/data
    networks:
      - catalyst-dev-network

  minio:
    image: minio/minio:latest
    container_name: senkou-catalyst-minio-dev
    restart: unless-stopped
    ports:
      - "${MINIO_S3_PORT:-9000}:9000"
      - "${MINIO_WEB_PORT:-9901}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_dev:/data
    networks:
      - catalyst-dev-network

networks:
  catalyst-dev-network:
    name: catalyst-dev-network
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  minio_data_dev:
    driver: local
