services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: senkou-catalyst-app
    restart: unless-stopped
    environment:
      - APP_PORT=5555
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-senkou_catalyst}
      - JWT_SECRET=${JWT_SECRET:-}
    depends_on:
      - postgres
    networks:
      - catalyst-network

  postgres:
    image: postgres:17-alpine
    container_name: senkou-catalyst-postgres-prod
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-}
      - POSTGRES_DB=${DB_NAME:-senkou_catalyst}
    networks:
      - catalyst-network
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: senkou-catalyst-cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol http2 run --token ${TUNNEL_TOKEN:-}
    networks:
      - catalyst-network

networks:
  catalyst-network:
    name: catalyst-network
    driver: bridge

volumes:
  postgres_data_prod:
    driver: local
